// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMatch(arg1) {
  return window['go']['service']['MatchService']['DeleteMatch'](arg1);
}

export function LoadMatches() {
  return window['go']['service']['MatchService']['LoadMatches']();
}

export function SaveMatch(arg1) {
  return window['go']['service']['MatchService']['SaveMatch'](arg1);
}
