// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteMatch(arg1:number):Promise<void>;

export function LoadMatches():Promise<Array<model.Match>>;

export function SaveMatch(arg1:model.Match):Promise<model.Match>;
