// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function LoadPlayers():Promise<Array<model.Player>>;

export function SavePlayer(arg1:string):Promise<model.Player>;
