// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadPlayers() {
  return window['go']['service']['PlayerService']['LoadPlayers']();
}

export function SavePlayer(arg1) {
  return window['go']['service']['PlayerService']['SavePlayer'](arg1);
}
